version: '3'
services:
  redis-server:
    image: redis
    container_name: redis-container
    restart: unless-stopped
    expose:
      - 6379
  node-app:
    depends_on:
      - redis-server
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    restart: on-failure
    ports:
      - "8787:8787"